//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace SPE.Api.Proxys {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarCIPMod1OperationCompleted;
        
        /// <remarks/>
        public Service() {
            this.Url = System.Configuration.ConfigurationManager.AppSettings["SPE_WebServiceTest_WSGeneral_Mod1"];
            //this.Url = "http://localhost:16558/Service.asmx";
        }
        
        /// <remarks/>
        public event ConsultarCIPMod1CompletedEventHandler ConsultarCIPMod1Completed;
        
        /// <remarks/>
        public event ActualizarCIPMod1CompletedEventHandler ActualizarCIPMod1Completed;
        
        /// <remarks/>
        public event EliminarCIPMod1CompletedEventHandler EliminarCIPMod1Completed;
        
        /// <remarks/>
        public event GenerarCIPMod1CompletedEventHandler GenerarCIPMod1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSConsultarCIPResponseMod1 ConsultarCIPMod1(BEWSConsultarCIPRequestMod1 request) {
            object[] results = this.Invoke("ConsultarCIPMod1", new object[] {
                        request});
            return ((BEWSConsultarCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsultarCIPMod1(BEWSConsultarCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsultarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSConsultarCIPResponseMod1 EndConsultarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSConsultarCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCIPMod1Async(BEWSConsultarCIPRequestMod1 request) {
            this.ConsultarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void ConsultarCIPMod1Async(BEWSConsultarCIPRequestMod1 request, object userState) {
            if ((this.ConsultarCIPMod1OperationCompleted == null)) {
                this.ConsultarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("ConsultarCIPMod1", new object[] {
                        request}, this.ConsultarCIPMod1OperationCompleted, userState);
        }
        
        private void OnConsultarCIPMod1OperationCompleted(object arg) {
            if ((this.ConsultarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCIPMod1Completed(this, new ConsultarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSActualizaCIPResponseMod1 ActualizarCIPMod1(BEWSActualizaCIPRequestMod1 request) {
            object[] results = this.Invoke("ActualizarCIPMod1", new object[] {
                        request});
            return ((BEWSActualizaCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginActualizarCIPMod1(BEWSActualizaCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ActualizarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSActualizaCIPResponseMod1 EndActualizarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSActualizaCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarCIPMod1Async(BEWSActualizaCIPRequestMod1 request) {
            this.ActualizarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void ActualizarCIPMod1Async(BEWSActualizaCIPRequestMod1 request, object userState) {
            if ((this.ActualizarCIPMod1OperationCompleted == null)) {
                this.ActualizarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("ActualizarCIPMod1", new object[] {
                        request}, this.ActualizarCIPMod1OperationCompleted, userState);
        }
        
        private void OnActualizarCIPMod1OperationCompleted(object arg) {
            if ((this.ActualizarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCIPMod1Completed(this, new ActualizarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSElimCIPResponseMod1 EliminarCIPMod1(BEWSElimCIPRequestMod1 request) {
            object[] results = this.Invoke("EliminarCIPMod1", new object[] {
                        request});
            return ((BEWSElimCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEliminarCIPMod1(BEWSElimCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSElimCIPResponseMod1 EndEliminarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSElimCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarCIPMod1Async(BEWSElimCIPRequestMod1 request) {
            this.EliminarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void EliminarCIPMod1Async(BEWSElimCIPRequestMod1 request, object userState) {
            if ((this.EliminarCIPMod1OperationCompleted == null)) {
                this.EliminarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("EliminarCIPMod1", new object[] {
                        request}, this.EliminarCIPMod1OperationCompleted, userState);
        }
        
        private void OnEliminarCIPMod1OperationCompleted(object arg) {
            if ((this.EliminarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCIPMod1Completed(this, new EliminarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSGenCIPResponseMod1 GenerarCIPMod1(BEWSGenCIPRequestMod1 request) {
            object[] results = this.Invoke("GenerarCIPMod1", new object[] {
                        request});
            return ((BEWSGenCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerarCIPMod1(BEWSGenCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSGenCIPResponseMod1 EndGenerarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSGenCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarCIPMod1Async(BEWSGenCIPRequestMod1 request) {
            this.GenerarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void GenerarCIPMod1Async(BEWSGenCIPRequestMod1 request, object userState) {
            if ((this.GenerarCIPMod1OperationCompleted == null)) {
                this.GenerarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("GenerarCIPMod1", new object[] {
                        request}, this.GenerarCIPMod1OperationCompleted, userState);
        }
        
        private void OnGenerarCIPMod1OperationCompleted(object arg) {
            if ((this.GenerarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarCIPMod1Completed(this, new GenerarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPSField;
        
        private string infoRequestField;
        
        /// <remarks/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <remarks/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        public string CIPS {
            get {
                return this.cIPSField;
            }
            set {
                this.cIPSField = value;
            }
        }
        
        /// <remarks/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSGenCIPResponseMod1 {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string xmlField;
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSGenCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string xmlField;
        
        /// <remarks/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <remarks/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSElimCIPResponseMod1 {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string infoResponseField;
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSElimCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPField;
        
        private string infoRequestField;
        
        /// <remarks/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <remarks/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        public string CIP {
            get {
                return this.cIPField;
            }
            set {
                this.cIPField = value;
            }
        }
        
        /// <remarks/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSActualizaCIPResponseMod1 {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string infoResponseField;
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSActualizaCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPField;
        
        private System.DateTime fechaExpiraField;
        
        private string infoRequestField;
        
        /// <remarks/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <remarks/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        public string CIP {
            get {
                return this.cIPField;
            }
            set {
                this.cIPField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaExpira {
            get {
                return this.fechaExpiraField;
            }
            set {
                this.fechaExpiraField = value;
            }
        }
        
        /// <remarks/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsCIPDetalleMod1 {
        
        private string idDetalleOrdenPagoField;
        
        private string conceptoPagoField;
        
        private string importeField;
        
        private string tipo_OrigenField;
        
        private string cod_OrigenField;
        
        private string campo1Field;
        
        private string campo2Field;
        
        private string campo3Field;
        
        /// <remarks/>
        public string IdDetalleOrdenPago {
            get {
                return this.idDetalleOrdenPagoField;
            }
            set {
                this.idDetalleOrdenPagoField = value;
            }
        }
        
        /// <remarks/>
        public string ConceptoPago {
            get {
                return this.conceptoPagoField;
            }
            set {
                this.conceptoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo_Origen {
            get {
                return this.tipo_OrigenField;
            }
            set {
                this.tipo_OrigenField = value;
            }
        }
        
        /// <remarks/>
        public string Cod_Origen {
            get {
                return this.cod_OrigenField;
            }
            set {
                this.cod_OrigenField = value;
            }
        }
        
        /// <remarks/>
        public string Campo1 {
            get {
                return this.campo1Field;
            }
            set {
                this.campo1Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo2 {
            get {
                return this.campo2Field;
            }
            set {
                this.campo2Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo3 {
            get {
                return this.campo3Field;
            }
            set {
                this.campo3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsCIPMod1 {
        
        private string idOrdenPagoField;
        
        private string idClienteField;
        
        private string numeroOrdenPagoField;
        
        private string orderIdComercioField;
        
        private string idMonedaField;
        
        private string totalField;
        
        private string fechaEmisionField;
        
        private string fechaCanceladoField;
        
        private string fechaConciliadoField;
        
        private string idEstadoConciliadoField;
        
        private string estadoConciliadoField;
        
        private string usuarioIDField;
        
        private string usuarioNombreField;
        
        private string usuarioApellidosField;
        
        private string usuarioAliasField;
        
        private string usuarioEmailField;
        
        private string dataAdicionalField;
        
        private string idEstadoField;
        
        private string estadoField;
        
        private BEWSConsCIPDetalleMod1[] detalleField;
        
        /// <remarks/>
        public string IdOrdenPago {
            get {
                return this.idOrdenPagoField;
            }
            set {
                this.idOrdenPagoField = value;
            }
        }
        
        /// <remarks/>
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroOrdenPago {
            get {
                return this.numeroOrdenPagoField;
            }
            set {
                this.numeroOrdenPagoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderIdComercio {
            get {
                return this.orderIdComercioField;
            }
            set {
                this.orderIdComercioField = value;
            }
        }
        
        /// <remarks/>
        public string IdMoneda {
            get {
                return this.idMonedaField;
            }
            set {
                this.idMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string FechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCancelado {
            get {
                return this.fechaCanceladoField;
            }
            set {
                this.fechaCanceladoField = value;
            }
        }
        
        /// <remarks/>
        public string FechaConciliado {
            get {
                return this.fechaConciliadoField;
            }
            set {
                this.fechaConciliadoField = value;
            }
        }
        
        /// <remarks/>
        public string IdEstadoConciliado {
            get {
                return this.idEstadoConciliadoField;
            }
            set {
                this.idEstadoConciliadoField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoConciliado {
            get {
                return this.estadoConciliadoField;
            }
            set {
                this.estadoConciliadoField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioID {
            get {
                return this.usuarioIDField;
            }
            set {
                this.usuarioIDField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioNombre {
            get {
                return this.usuarioNombreField;
            }
            set {
                this.usuarioNombreField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioApellidos {
            get {
                return this.usuarioApellidosField;
            }
            set {
                this.usuarioApellidosField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioAlias {
            get {
                return this.usuarioAliasField;
            }
            set {
                this.usuarioAliasField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioEmail {
            get {
                return this.usuarioEmailField;
            }
            set {
                this.usuarioEmailField = value;
            }
        }
        
        /// <remarks/>
        public string DataAdicional {
            get {
                return this.dataAdicionalField;
            }
            set {
                this.dataAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public string IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public BEWSConsCIPDetalleMod1[] Detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarCIPResponseMod1 {
        
        private string xMLField;
        
        private string estadoField;
        
        private string mensajeField;
        
        private BEWSConsCIPMod1[] cIPsField;
        
        private string infoResponseField;
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public BEWSConsCIPMod1[] CIPs {
            get {
                return this.cIPsField;
            }
            set {
                this.cIPsField = value;
            }
        }
        
        /// <remarks/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ConsultarCIPMod1CompletedEventHandler(object sender, ConsultarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSConsultarCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSConsultarCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ActualizarCIPMod1CompletedEventHandler(object sender, ActualizarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSActualizaCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSActualizaCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EliminarCIPMod1CompletedEventHandler(object sender, EliminarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSElimCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSElimCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GenerarCIPMod1CompletedEventHandler(object sender, GenerarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSGenCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSGenCIPResponseMod1)(this.results[0]));
            }
        }
    }
}
